# Generated by Django 3.2.12 on 2022-02-20 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='email',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='password',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='phone',
            field=models.IntegerField(default=False, max_length=12),
        ),
    ]
