# Generated by Django 3.2.12 on 2022-02-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220220_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default=False, max_length=10),
        ),
    ]
